### ISSUE TITLE
Running 2019 PloS Comp Biol iron metabolism model of Parmar and Mendes

### ISSUE THREAD

**Issue by radivot** [jonasfoe/copasi-r-api#5]
Wondering if you could guide me to getting this code to give time course results.
The cps files are here [cpsFiles.zip](https://github.com/jpahle/CoRC/files/2901333/cpsFiles.zip)

library(CoRC)
unloadAllModels()
(L=loadExamples())
runTC(model=L[[1]]) #runs fine
path="~/ccf/jarek/grants/msb/iron/parmar19sup/cps/"
(m0=loadModel(paste0(path,"IronMousePV3.cps")))
runTC(model=m0) # no results
(m1=loadModel(paste0(path,"IronMousePV3_Hemochromatosis.cps")))
runTC(model=m1) # no results

**Comment by jonasfoe** [comment]
Hey radivot,

those models have save result in memory for the time course task disabled.
You can use `runTC(save_result_in_memory = TRUE, model=m0)`.

Unfortunately, this is one of the easiest traps for fall into when trying out CoRC with certain models.
If you open the .cps file in Copasi and run the task, the result table will also be empty.

Best,
Jonas

**Comment by radivot** [comment]
wonderful! thank you, it now works great!
